# Generated by Django 3.1 on 2020-09-01 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Pattern',
            new_name='CodeSnippet',
        ),
    ]
